try:
#     function(3)
#     function1(5)
# except ZeroDivisionError:
#     print("Error: ZeroDivisionError and handled.")
# except NameError:
#     print("Error: NameError ocucred and handled.")